name: Car_Wave
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  google_fonts: ^6.1.0
  provider: ^6.0.5
  url_launcher: ^6.1.7
  share_plus: ^7.1.0
  flutter_native_splash: ^2.3.2
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.2.3
  device_preview: ^1.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  change_app_package_name: ^1.1.0
  transparent_image: ^2.0.1
  flutter_riverpod: ^2.3.6
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.3.10
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_native_splash:
  background_image: "images/splashBackgroung.png"
  image: images/splash-logo.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
