name: world_car
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_nav_bar: ^5.0.6
  google_fonts: ^4.0.3
  provider: ^6.0.5
  url_launcher: ^6.1.7
  share_plus: ^6.3.0
  flutter_native_splash: ^2.2.16
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.2.3
  device_preview: ^1.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  change_app_package_name: ^1.1.0
  transparent_image: ^2.0.1
  flutter_riverpod: ^2.3.6

dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/512.png"

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#181721"
  image: images/Logo.png

flutter:
  uses-material-design: true

  assets:
    - images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
